export const FETCH_CHARACTERS_BEGIN = "FETCH_CHARACTERS_BEGIN";
export const FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS";
export const FETCH_CHARACTERS_FAILURE = "FETCH_CHARACTERS_FAILURE";
export const FETCH_CHARACTER_EPISODES_SUCCESS =
  "FETCH_CHARACTER_EPISODES_SUCCESS";
export const FETCH_CHARACTER_EPISODES_FAILURE =
  "FETCH_CHARACTER_EPISODES_FAILURE";

export const FETCH_EPISODES_SUCCESS = "FETCH_EPISODES_SUCCESS";

export const FETCH_LOCATIONS_SUCCESS = "FETCH_EPISODES_SUCCESS";

export const SET_CHARACTERS_CURRENT_PAGE = "SET_CHARACTERS_CURRENT_PAGE";
export const SET_EPISODES_CURRENT_PAGE = "SET_EPISODES_CURRENT_PAGE";
export const SET_LOCATIONS_CURRENT_PAGE = "SET_LOCATIONS_CURRENT_PAGE";
