export const FETCH_CHARACTERS_BEGIN = "FETCH_CHARACTERS_BEGIN";
export const FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS";
export const FETCH_CHARACTERS_FAILURE = "FETCH_CHARACTERS_FAILURE";
export const FETCH_CHARACTER_BEGIN = "FETCH_CHARACTER_BEGIN";
export const FETCH_CHARACTER_SUCCESS = "FETCH_CHARACTER_SUCCESS";

export const FETCH_EPISODES_BEGIN = "FETCH_EPISODES_BEGIN";
export const FETCH_EPISODES_SUCCESS = "FETCH_EPISODES_SUCCESS";
export const FETCH_EPISODES_FAILURE = "FETCH_EPISODES_FAILURE";
export const FETCH_EPISODE_BEGIN = "FETCH_EPISODE_BEGIN";
export const FETCH_EPISODE_SUCCESS = "FETCH_EPISODE_SUCCESS";

export const FETCH_LOCATION_BEGIN = "FETCH_LOCATION_BEGIN";
export const FETCH_LOCATION_SUCCESS = "FETCH_LOCATION_SUCCESS";
export const FETCH_LOCATIONS_SUCCESS = "FETCH_EPISODES_SUCCESS";
export const FETCH_LOCATIONS_BEGIN = "FETCH_LOCATIONS_BEGIN";
export const FETCH_LOCATIONS_FAILURE = "FETCH_LOCATIONS_FAILURE";

export const SET_CHARACTERS_CURRENT_PAGE = "SET_CHARACTERS_CURRENT_PAGE";
export const SET_EPISODES_CURRENT_PAGE = "SET_EPISODES_CURRENT_PAGE";
export const SET_LOCATIONS_CURRENT_PAGE = "SET_LOCATIONS_CURRENT_PAGE";
